services:
  - type: web
    name: lieblingsfilme-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://tobertsenger:AyskuJXQz0ccJBsR@cluster0.ftzuofq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    autoDeploy: true
